#当前使用的环境
[server]
	runMode="dev"
	#可以指定正则表达式也可以直接:13000默认使用0.0.0.0的IP(不建议)^10\\.83\\.\\d+\\.\\d+$:13000
	bindAddress="^10\\.0\\.\\d+.\\d+:13000"
	compress="snappy"

[client]
	runMode="dev"
	compress="snappy"
	selectorStrategy="random"

#cluster的服务器
[clusters]
	[clusters.dev]
		registry="zk://localhost:2181"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=10
		#读取缓冲大小 
		readBufferSize=16384 
		#写入缓冲大小
		writeBufferSize=16384 
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
