# This is a TOML document.


#当前使用的环境
[env]
name="moa-demo"
appSecretKey="123"
runMode="dev"
#可以是momokeeper或者zookeeper
registryType="zookeeper" 
#service Uri的后缀可以为空
serviceUriSuffix=""


#registry的管理	
[registry]
	[registry.dev]
		hosts="localhost:2181"
	[registry.online]
		hosts="vm-bibi-zk-mq001.vm:2181,vm-bibi-zk-mq002.vm:2181,vm-bibi-zk-mq003.vm:2181" 

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		processTimeout=5
		#每个机器的连接数量
		poolSizePerHost = 5
		logFile="../conf/log_test.xml"
		#连接选择方式random或ketama
		selectorStrategy="ketama"
	[clusters.online]
		#env=dev/online
		env="online" 
		processTimeout=5
		#每个机器的连接数量
		poolSizePerHost = 5
		logFile="../conf/log_test.xml"
		#连接选择方式random或ketama
		selectorStrategy="ketama"

