# This is a TOML document.


#当前使用的环境
[env]
name="moa-demo"
runMode="dev"
#bindAddress="^10\\.83\\.\\d+\\.\\d+$:13000"
bindAddress="10.0.1.181:13000"

#groupId 标识服务所属集群
groupId="*" 

#registry的管理	
[registry]
	[registry.dev]
		hosts="zk://localhost:2181"

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		logFile="../conf/log_test.xml"
		processTimeout=5
		#最大分发处理协程数
		maxDispatcherSize=8000 
		#读取缓冲大小 
		readBufferSize=16384 
		#写入缓冲大小
		writeBufferSize=16384 
		#写异步channel长度
		writeChannelSize=1000 
		#读异步channel长度
		readChannelSize=1000 
