#当前使用的环境
[env]
name="moa-demo"
appSecretKey="123"
runMode="dev"

#registry的管理	
[registry]
	[registry.dev]
		hosts="zk://localhost:2181"

#cluster的服务器
[clusters]
	[clusters.dev]
		#env=dev/online
		env="dev" 
		processTimeout=5
		#每个机器的连接数量
		poolSizePerHost = 5
		logFile="../conf/log_test.xml"
		#连接选择方式random或ketama
		selectorStrategy="ketama"
